Document: ucimf
Title: Debian ucimf Manual
Author: <insert document author here>
Abstract: This manual describes what ucimf is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ucimf/ucimf.sgml.gz

Format: postscript
Files: /usr/share/doc/ucimf/ucimf.ps.gz

Format: text
Files: /usr/share/doc/ucimf/ucimf.text.gz

Format: HTML
Index: /usr/share/doc/ucimf/html/index.html
Files: /usr/share/doc/ucimf/html/*.html

  
