#!/bin/bash
#
#  This is a execution wrapper. 
#

export PREFIX=YOUR_COSTOM_PATH;
export CONSOLE_APP=jfbterm  # Choices: dummy, jfbterm, fbiterm,...
export LC_CTYPE=zh_TW.UTF-8 ;
export LD_LIBRARY_PATH=$PREFIX/lib/ ;
export PATH=$PREFIX/bin/:$PATH ;
export OVMODULE_DIR=$PREFIX/lib/openvanilla/ ;
export IMF_MODULE_DIR=$PREFIX/lib/ucimf/ ;

export UCIMF_FONTPATH=/usr/share/fonts/truetype/arphic/ukai.ttf ;
#export UCIMF_FONTPATH=/usr/X11R6/lib/X11/fonts/misc/b16_b.pcf.gz ;

exec $PREFIX/bin/$CONSOLE_APP
